name = "cf-workers-tester"
compatibility_date = "2023-10-10"
node_compat = true

vars = { ENVIRONMENT = "development" }

main = "dist/main.js"

[build]
command = "npm run build"

[site]
bucket = "./public"
